cmd_/home/nayeem/Desktop/DirectFB/linux-fusion-9.0.3/one/list.o := gcc -Wp,-MD,/home/nayeem/Desktop/DirectFB/linux-fusion-9.0.3/one/.list.o.d  -nostdinc -isystem /usr/lib/gcc/i686-linux-gnu/4.8/include  -I/usr/src/linux-headers-3.13.0-46-generic/arch/x86/include -Iarch/x86/include/generated  -Iinclude -I/usr/src/linux-headers-3.13.0-46-generic/arch/x86/include/uapi -Iarch/x86/include/generated/uapi -I/usr/src/linux-headers-3.13.0-46-generic/include/uapi -Iinclude/generated/uapi -include /usr/src/linux-headers-3.13.0-46-generic/include/linux/kconfig.h -Iubuntu/include  -D__KERNEL__ -I/home/nayeem/Desktop/DirectFB/linux-fusion-9.0.3/one -I/home/nayeem/Desktop/DirectFB/linux-fusion-9.0.3/one/single -I/home/nayeem/Desktop/DirectFB/linux-fusion-9.0.3/include -I/home/nayeem/Desktop/DirectFB/linux-fusion-9.0.3/linux/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -O2 -m32 -msoft-float -mregparm=3 -freg-struct-return -mno-mmx -mno-sse -fno-pic -mpreferred-stack-boundary=2 -march=i686 -mtune=generic -maccumulate-outgoing-args -Wa,-mtune=generic32 -ffreestanding -fstack-protector -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -Wframe-larger-than=1024 -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -pg -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -DCC_HAVE_ASM_GOTO  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(list)"  -D"KBUILD_MODNAME=KBUILD_STR(linux_one)" -c -o /home/nayeem/Desktop/DirectFB/linux-fusion-9.0.3/one/.tmp_list.o /home/nayeem/Desktop/DirectFB/linux-fusion-9.0.3/one/list.c

source_/home/nayeem/Desktop/DirectFB/linux-fusion-9.0.3/one/list.o := /home/nayeem/Desktop/DirectFB/linux-fusion-9.0.3/one/list.c

deps_/home/nayeem/Desktop/DirectFB/linux-fusion-9.0.3/one/list.o := \

/home/nayeem/Desktop/DirectFB/linux-fusion-9.0.3/one/list.o: $(deps_/home/nayeem/Desktop/DirectFB/linux-fusion-9.0.3/one/list.o)

$(deps_/home/nayeem/Desktop/DirectFB/linux-fusion-9.0.3/one/list.o):
